# Generated by Django 3.2.3 on 2021-09-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly_flippers_app', '0003_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
