# Generated by Django 3.2.3 on 2021-09-10 23:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fly_flippers_app', '0002_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=cloudinary.models.CloudinaryField(default='null', max_length=255, verbose_name='image'),
        ),
    ]
