# Generated by Django 3.2.3 on 2021-09-11 13:01

from django.db import migrations, models
import fly_flippers_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('fly_flippers_app', '0004_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(max_length=25, validators=[fly_flippers_app.models.validateLengthGreaterThanTwo]),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(validators=[fly_flippers_app.models.validateLengthGreaterThanTwo]),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(max_length=45, validators=[fly_flippers_app.models.validateLengthGreaterThanTwo]),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, validators=[fly_flippers_app.models.validateLengthGreaterThanTwo]),
        ),
    ]
