# Generated by Django 3.2.3 on 2021-09-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly_flippers_app', '0009_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
