# Generated by Django 3.2.3 on 2021-09-20 21:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fly_flippers_app', '0010_item_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
